name: Process CSV

on:
  push:
    branches: [ main ]
    paths:
      - database_information.csv   # only run if this file changes

permissions:
  contents: write   # 👈 allow pushing commits

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas

      - name: Run CSV processor
        run: python scripts/process_csv.py

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add spreadsheetInfo.json
          git commit -m "Update spreadsheetInfo.json" || echo "No changes to commit"
          git push
